version: '3.8'

services:
  omada-controller:
    image: mbentley/omada-controller
    container_name: omada-controller
    environment:
      - PUID=508
      - PGID=508
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8843
      - PORT_APP_DISCOVERY=27001
      - PORT_ADOPT_V1=29812
      - PORT_UPGRADE_V1=29813
      - PORT_MANAGER_V1=29811
      - PORT_MANAGER_V2=29814
      - PORT_DISCOVERY=29810
      - PORT_TRANSFER_V2=29815
      - PORT_RTTY=29816
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
      #- SSL_CERT_NAME=tls.crt
      #- SSL_KEY_NAME=tls.key
      - TZ=Etc/UTC
    ports:
      - "8088:8088"
      - "8043:8043"
      - "27001:27001/udp"
      - "27002:27002"
      - "29810:29810/udp"
      - "29811:29811"
      - "29812:29812"
      - "29813:29813"
      - "29814:29814"
      - "29815:29815"
      - "29816:29816"
    volumes:
      - ./docker-volumes/data:/opt/tplink/EAPController/data
      - ./docker-volumes/work:/opt/tplink/EAPController/work
      - ./docker-volumes/logs:/opt/tplink/EAPController/logs
    restart: unless-stopped
