version: '3'

services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-volumes/configs:/app/data/configs
      - ./docker-volumes/icons:/app/public/icons
      - ./docker-volumes/data:/data
    ports:
      - '80:7575'