version: '3.8'

services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      # - "68:68/tcp" # Disable this because we are not using DHCP
      # - "68:68/udp" # Disable this because we are not using DHCP
      - "3000:3000/tcp"
    volumes:
      - ./docker-volumes/work:/opt/adguardhome/work
      - ./docker-volumes/conf:/opt/adguardhome/conf
    restart: unless-stopped